"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var InCartController_1 = require("../controllers/InCartController");
var routes = (0, express_1.Router)();
routes.get('/', InCartController_1.default.getProductInCart);
routes.post('/', InCartController_1.default.addToIncart);
routes.delete('/', InCartController_1.default.deleteInCart);
routes.patch('/', InCartController_1.default.takeToOrder);
exports.default = routes;
